### ISSUE TITLE
add_dockerfile_shinyproxy and BiocManager

### ISSUE THREAD

**Issue by stheil15** [ThinkR-open/golem#715] opened 2021-07-30 15:09 UTC
add_dockerfile_shinyproxy funciton do not add correct lines to install BiocManager packages.

**Comment by VincentGuyader** [comment] 2021-07-30 19:11
Hi

Can you please send me your DESCRIPTION file ?

It will help me to implement this. 
Regards

**Comment by stheil15** [comment] 2021-08-17 08:04
Here is a [link](https://filesender.renater.fr/?s=download&token=a0d5a516-8f0b-44b5-b01b-a97d7bfbcc90) to the DESCRIPTION file.

Thanks

**Comment by ColinFay** [comment] 2021-09-24 08:34
I think it's a duplicate of https://github.com/ColinFay/dockerfiler/issues/16, so I'm closing this for now :) 

Feel free to comment if you want me to reopen. 

Cheers, 
Colin

**Closed by ColinFay** 2021-09-24 08:34 UTC
