### ISSUE TITLE
Reload app on minor changes

### ISSUE THREAD

**Issue by nvelden** [ThinkR-open/golem#627] opened 2021-03-17 08:14 UTC
My usual workflow for writing an App is to run the app and when I add for instance a control widget or add a CSS rule I hit refresh in the browser to see how things look.  With a Golem App using modules this does not seem to work. For every small change do I need to stop the App and then restart by running the appdemo::run_app() in the run_dev.R file? Is there a better workflow?

**Comment by ColinFay** [comment] 2021-03-17 09:05
Hey, 

Does this https://github.com/ThinkR-open/golem/issues/263#issuecomment-773217754 answer your question ?

**Comment by nvelden** [comment] 2021-03-18 10:56
Thanks a lot. I followed the steps outlined in your description. I can see that the browser refreshes after adding an input in a module and press save but the change is not shown in the web browser. Only when I run the run_dev.R file again the change pops-up.

**Comment by ColinFay** [comment] 2021-04-02 08:15
Hey @nvelden, 

I'm closing this as it is a duplicate of #263 and I feel like we should keep track of this feature in one place :) 

Thanks for opening this issue, 

Cheers, 

Colin

**Closed by ColinFay** 2021-04-02 08:15 UTC
