### ISSUE TITLE
feat: remove {rstudioapi} hard desc

### ISSUE THREAD

**Issue by VincentGuyader** [ThinkR-open/golem#950] opened 2022-12-08 16:43 UTC
to lower the number of packages to install to deploy à shiny app.

**Comment by ColinFay** [comment] 2022-12-08 17:15
Duplicate of #940 :)

**Comment by ColinFay** [comment] 2022-12-08 17:17
Some work already here : https://github.com/ThinkR-open/golem/commit/53b14d9817247abe0c4e7fa5ca6e489fdd1123da 

but it will be worth starting from a fresh clean branch :)

**Closed** 2022-12-12 09:37 UTC
Labels: enhancement
