### ISSUE TITLE
Using golem with renv causes an obscure error

### ISSUE THREAD

**Issue by dwhdai** [ThinkR-open/golem#557] opened 2020-11-12 15:40 UTC
Hello!

When creating golem apps in an renv project, I get this weird error:

![image](https://user-images.githubusercontent.com/16040965/98961235-58b6b380-24d3-11eb-8307-25a160b63368.png)

The only resolution is to delete the renv cache and reinstall the packages in the cache. Just wondering if anyone else has experienced this?

**Comment by cderv** [comment] 2020-11-12 16:00
I think this is related: https://github.com/rstudio/renv/issues/455

**Comment by dwhdai** [comment] 2020-11-12 19:47
> I think this is related: [rstudio/renv#455](https://github.com/rstudio/renv/issues/455)

Thanks for flagging that issue! Looks like it might be an `renv` issue then. I'll leave this open for visibility for others (in case mods think otherwise), as I've only experienced this issue when using `renv` in conjunction with `golem`.

**Comment by jaredlander** [comment] 2020-11-16 20:59
Just experienced this myself. I deleted `{golem}` from the `{renv}` cache and that seemed to fix things. But I have no basis why it fixed anything or if that was really the problem anyway.

**Comment by jaredlander** [comment] 2020-11-16 21:05
I take that back. After successfully loading one package, trying to load `{shiny}` failed still. This is getting more complicated.

**Comment by jaredlander** [comment] 2020-11-16 21:09
Sorry for the scattershot comments, I'm just on the tailend of debugging this for about an hour. Some packages can be installed and loaded, others can't. So far `{bs4Dash}` works while `{shiny}` and `{leaflet}` don't. It's getting weirder.

**Comment by dwhdai** [comment] 2020-11-17 02:11
@jaredlander what worked for me in the past was deleting the entire `{renv}` cache folder ([location specific to your OS](https://rstudio.github.io/renv/reference/paths.html)) and then re-installing everything with `renv::restore()`. It's time consuming... but at least it's a reproducible environment thanks to `{renv}`

**Comment by jaredlander** [comment] 2020-11-17 02:37
I might be going down that road but wanted to help @kevinushey debug what's happening.

**Comment by kevinushey** [comment] 2020-11-17 05:06
This is caused by a bug present in the CRAN release of `golem` but is currently fixed in the development version of `golem`. See https://github.com/rstudio/renv/issues/455 for my investigation.

I'd recommend updating `golem` on CRAN ASAP since currently this implies anyone trying to use `golem` + `renv` together risks corrupting their `renv` package cache.

**Comment by jaredlander** [comment] 2020-11-17 12:17
Thanks @kevinushey for figuring it out. Tagging @ColinFay about updating CRAN.

**Comment by ColinFay** [comment] 2020-12-11 08:22
Thank you all for this thread and thanks a lot to @kevinushey for the deep inspection. 

The new version of `{golem}` should be on the CRAN soon, I'm doing a last round up of issue solving right now and will send it to CRAN whenever this version is stable. 

Cheers, 
Colin

**Comment by ColinFay** [comment] 2021-04-28 11:52
Hey y'all, 

I'm sorry it took so long for pushing the new version to CRAN. 

The new version (0.3.1) has been available for two weeks now, feel free to update :) 

I'm going to close this now, if ever you still encounter this issue after an update, please leave a comment below so that I can reopen it. 

Cheers, 

Colin

**Closed by ColinFay** 2021-04-28 11:52 UTC
