### ISSUE TITLE
Are golem and shinydashboard incompatible?

### ISSUE THREAD

**Issue by tleers** [ThinkR-open/golem#277] opened 2019-11-10 20:52 UTC
Is there any way to combine golem and shinydashboard?

If I use:
ui <- tagList(dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody()
))
I can run the app, and everything works fine, except for the fact that all content from different tabs are put into a single page. In other words, the switching between tabs, a crucial feature of shinydashboard, no longer functions.

If I do not use tagList, like so:
dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody()
)
I receive the following error:
Error in tagAssert(header, type = "header", class = "main-header") : 
  Expected tag to be of type header

Are they fundamentally incompatible?

**Comment by ColinFay** [comment] 2019-11-14 20:36
Hey, 

An app built with `{golem}` is a shiny app and every template will work with `{golem}`. 

Here is an example of a shiny dashboard example built with `{golem}`: https://github.com/ColinFay/golemize/tree/master/shiny-dashboard

Can you tell me more about what you're doing differently?

**Comment by ColinFay** [comment] 2019-11-25 20:27
@tleers Did you get any chance to have a look at the example?

**Comment by tleers** [comment] 2019-12-15 16:51
@ColinFay Hi Colin, sorry for the late reply. Your example helped me figure out my issue. I didn't use the correct structure in my app. Thanks again!

**Comment by ColinFay** [comment] 2019-12-20 09:09
Perfect. 

Closing then

**Comment by Benelaus** [comment] 2020-02-07 22:38
@tleers Could you expand on how your app structure was flawed? We are experiencing the same problem that you had. Thanks!

**Comment by ColinFay** [comment] 2020-02-07 23:32
@Benelaus can you provide a reproducible example please?

Have you looked at : https://github.com/ColinFay/golemize/tree/master/shiny-dashboard ?

**Comment by mohitsahasrabudhe** [comment] 2020-02-11 16:16
Adding a bootstrap or jquery htmltools::htmlDependency to the UI cause the dashboard to disregard shinydashboard tabs when loaded using run_app()


```
library(shiny)
library(shinydashboard)

app_ui <- function(request) {
  tagList(
    htmltools::htmlDependency("bootstrap", "3.4.1",
                              src = here::here("bootstrap"),
                              script = "bootstrap.min.js"),
    # Leave this function for adding external resources
    golem_add_external_resources(),
    # List the first level UI elements here 
    dashboardPage(
      dashboardHeader(title = "Basic dashboard"),
      dashboardSidebar(
        sidebarMenu(
          menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard")),
          menuItem("Widgets", tabName = "widgets", icon = icon("th"))
        )
      ),
      dashboardBody(
      tabItems(
          # First tab content
          tabItem(tabName = "dashboard",
                  fluidRow(
                    box(plotOutput("plot1", height = 250)),
                    
                    box(
                      title = "Controls",
                      sliderInput("slider", "Number of observations:", 1, 100, 50)
                    )
                  )
          ),
          
          # Second tab content
          tabItem(tabName = "widgets",
                  h2("Widgets tab content")
          )
        ))
      
    )
  )
}

#' @import shiny
golem_add_external_resources <- function(){
  
  addResourcePath(
    'www', system.file('app/www', package = "golemdashboard")
  )
  
  tags$head(
    golem::activate_js(),
    golem::favicon(),
    tags$title("golemdashboard")
    # Add here all the external resources
    # If you have a custom.css in the inst/app/www
    # Or for example, you can add shinyalert::useShinyalert() here
    #tags$link(rel="stylesheet", type="text/css", href="www/custom.css")
    
  )
}
```

**Comment by mohitsahasrabudhe** [comment] 2020-02-11 21:19
Adding a bootstrap or jquery htmltools::htmlDependency to the UI cause the dashboard to disregard shinydashboard tabs and follow a vertical layout when loaded using run_app()

```
library(shiny)
library(shinydashboard)

app_ui <- function(request) {
  tagList(
    htmltools::htmlDependency("bootstrap", "3.4.1",
                              src = here::here("bootstrap"),
                              script = "bootstrap.min.js"),
    # Leave this function for adding external resources
    golem_add_external_resources(),
    # List the first level UI elements here 
    dashboardPage(
      dashboardHeader(title = "Basic dashboard"),
      dashboardSidebar(
        sidebarMenu(
          menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard")),
          menuItem("Widgets", tabName = "widgets", icon = icon("th"))
        )
      ),
      dashboardBody(
      tabItems(
          # First tab content
          tabItem(tabName = "dashboard",
                  fluidRow(
                    box(plotOutput("plot1", height = 250)),
                    
                    box(
                      title = "Controls",
                      sliderInput("slider", "Number of observations:", 1, 100, 50)
                    )
                  )
          ),
          
          # Second tab content
          tabItem(tabName = "widgets",
                  h2("Widgets tab content")
          )
        ))
    )
  )
}

#' @import shiny
golem_add_external_resources <- function(){
  
  addResourcePath(
    'www', system.file('app/www', package = "golemdashboard")
  )
  
  tags$head(
    golem::activate_js(),
    golem::favicon(),
    tags$title("golemdashboard")
    # Add here all the external resources
    # If you have a custom.css in the inst/app/www
    # Or for example, you can add shinyalert::useShinyalert() here
    #tags$link(rel="stylesheet", type="text/css", href="www/custom.css")
  )
}
```

**Comment by ColinFay** [comment] 2020-09-04 22:26
Hey, 

Thanks for the reprex about the external dep to bootstrap

I think the Bootstrap and jQuery htmldependency is not a {golem} related problem but will arise in any `{shiny}` application, so I'm closing this for now, as it relates more to `{shiny}` itself :) 

Cheers, 
Colin

**Closed by ColinFay** 2020-09-04 22:26 UTC

**Comment by albersonmiranda** [comment] 2021-05-24 21:31
Hey y'all!

Turns out, it seems dynamic boxes won't work with {golem}. Check out this `valueBox()` example from [{shinydashboard} documentation](https://rstudio.github.io/shinydashboard/structure.html#valuebox):

```
#' name_of_module1 UI Function
#'
#' @description A shiny Module.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#'
#' @noRd 
#'
#' @importFrom shiny NS tagList 
mod_name_of_module1_ui <- function(id){
  ns <- NS(id)
  tagList(
 
    fluidRow(
      # A static valueBox
      valueBox(10 * 2, "New Orders", icon = icon("credit-card")),
      
      # Dynamic valueBoxes
      valueBoxOutput("progressBox"),
      
      valueBoxOutput("approvalBox")
    ),
    fluidRow(
      # Clicking this will increment the progress amount
      box(width = 4, actionButton("count", "Increment progress"))
    )
    
  )
}
    
#' name_of_module1 Server Functions
#'
#' @noRd 
mod_name_of_module1_server <- function(id){
  moduleServer( id, function(input, output, session){
    ns <- session$ns
 
    output$progressBox <- renderValueBox({
      valueBox(
        paste0(25 + input$count, "%"), "Progress", icon = icon("list"),
        color = "purple"
      )
    })
    
    output$approvalBox <- renderValueBox({
      valueBox(
        "80%", "Approval", icon = icon("thumbs-up", lib = "glyphicon"),
        color = "yellow"
      )
    })
    
  })
}
    
## To be copied in the UI
# mod_name_of_module1_ui("name_of_module1_ui_1")
    
## To be copied in the server
# mod_name_of_module1_server("name_of_module1_ui_1")
```
Static boxes will render, while server side ones won't.

**Comment by ColinFay** [comment] 2021-05-25 05:21
Hey @albersonmiranda, 

That has nothing to do with `{golem}` — your code won’t work outside of `{golem}` either ;)

You need to add `ns()` to the output ids in your modules to make them work. 

Cheers, 
Colin

**Comment by albersonmiranda** [comment] 2021-05-25 11:23
And the inputs ids too... Gee, six months into this and I still forget it. My bad 🤦
