### ISSUE TITLE
Creating app template within desired path

### ISSUE THREAD

**Issue by rpodcast** [ThinkR-open/golem#24] opened 2019-03-21 04:18 UTC
This may be another "niche" case but consider this situation I often deal with: 

I use `packrat` to manage the package dependencies for any app that I want deployed to my `$day_job` internal Shiny server pro.  First I set up a version-controlled (git) packrat project, then install `shiny` and `golem`.  Within that app's project dir, I run `golem::create_shiny_template(path = ".", check_name = FALSE)`.  I'm noticing that when I choose the option to overwrite the path, the command hangs and I have to manually kill the process.  I see that indeed the template files were created, but the git repository becomes corrupted:

```
$ git status
error: bad index file sha1 signature
fatal: index file corrupt
```

I'm in a bit of a conundrum because I have to use my app's packrat library to hold the `golem` installation, and that means I have to launch R in that directory.  I'm wondering if there is a way that within `create_shiny_template` it detects that the user's working directory for launching the function is indeed the same as the desired "path", and if it is, then don't try re-creating the directory but instead just copy all of the template files over, and make sure the app name (i.e. the package name) is the same as the current working directory name?  I hope that makes sense but I'm happy to elaborate further.

**Comment by rpodcast** [comment] 2019-03-21 23:19
I thought about this more on the :car: home and one approach might be to simply route the template files to a temp directory and copy them back to the current working dir, ensuring that the tmpdir path uses the same "destination" directory name as the current working directory.  I realize not many users will have to go through this so I'd be happy to contribute a PR to help.

**Comment by ColinFay** [comment] 2019-06-29 08:33
@rpodcast can you still reproduce this behavior?

**Comment by ColinFay** [comment] 2019-11-27 20:54
I can reproduce that. 

Might be because there exists another older git index which is now corrupted by the creation of new files.

**Comment by ColinFay** [comment] 2021-11-05 15:26
This seems to be resolved via recent changes in `create_golem()`


```r
colin:tmp colin$ Rscript -e "golem::create_golem('pouet')"
── Checking package name 
✔ Valid package name
── Creating dir 
✔ Created package directory
── Copying package skeleton 
✔ Copied app skeleton
── Setting the default config 
✔ Configured app
── Running project hook function 
✔ All set
✔ Setting active project to '/private/tmp/pouet'
── Done 
A new golem named pouet was created at /private/tmp/pouet .
To continue working on your app, start editing the 01_start.R file.
colin:tmp colin$ cd pouet 
colin:pouet colin$ git init
Initialized empty Git repository in /private/tmp/pouet/.git/
colin:pouet colin$ cd ..
colin:tmp colin$ Rscript -e "golem::create_golem('pouet')"

colin:tmp colin$ Rscript -e "golem::create_golem('pouet', overwrite = TRUE)"
── Checking package name 
✔ Valid package name
• Overwriting existing project.
── Copying package skeleton 
✔ Copied app skeleton
── Setting the default config 
✔ Configured app
── Running project hook function 
✔ All set
✔ Setting active project to '/private/tmp/pouet'
── Done
A new golem named pouet was created at /private/tmp/pouet .
To continue working on your app, start editing the 01_start.R file.
colin:tmp colin$ cd pouet/
colin:pouet colin$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .Rbuildignore
        DESCRIPTION
        NAMESPACE
        R/
        dev/
        inst/
        man/

nothing added to commit but untracked files present (use "git add" to track)
```

**Closed by ColinFay** 2021-11-05 15:26 UTC
Labels: bug
