### ISSUE TITLE
[BUG] when you put a dot in your package name, golem will create a subfolder...

### ISSUE THREAD

**Issue by VincentGuyader** [ThinkR-open/golem#985] opened 2023-02-08 10:57 UTC
**Describe the bug**

when you put a dot in your package name, golem will create a subfolder...

**To Reproduce**

golem::create_golem(package_name = "toto.bidul",path = "hop")

this produce a golem inside "hop/toto/bidul",

 instead of "hop/todo.bidul"

**Comment by ColinFay** [comment] 2023-02-08 11:52
This seems to be windows related, I can't reproduce on Mac : 

```
colinfay@Colins-MBP /tmp % Rscript -e 'golem::create_golem(package_name = "toto.bidul",path = "hop")'
── [.Rprofile] Sourcing user-wide rprofile ─────────────────────
── Checking package name ─────────────────────
✔ Valid package name
── Creating dir ─────────────────────
✔ Creating 'hop/'
✔ Setting active project to '/private/tmp/hop'
✔ Creating 'R/'
✔ Writing a sentinel file '.here'
• Build robust paths within your project via `here::here()`
• Learn more at <https://here.r-lib.org>
✔ Setting active project to '<no active project>'
✔ Created package directory
── Copying package skeleton ─────────────────────
✔ Copied app skeleton
── Setting the default config ─────────────────────
✔ Configured app
── Running project hook function ─────────────────────
✔ All set
✔ Setting active project to '/private/tmp/hop'
── Done ─────────────────────
A new golem named toto.bidul was created at /private/tmp/hop .
To continue working on your app, start editing the 01_start.R file.
Warning message:
In normalizePath(path) : path[1]="hop": No such file or directory

colinfay@Colins-MBP /tmp % ls hop 
DESCRIPTION	NAMESPACE	R		dev		inst		man

colinfay@Colins-MBP /tmp % cat hop/DESCRIPTION 
Package: toto.bidul
Title: An Amazing Shiny App
Version: 0.0.0.9000
Authors@R: 
    person(given = "firstname",
           family = "lastname",
           role = c("aut", "cre"),
           email = "your@email.com")
Description: What the package does (one paragraph).
License: What license is it under?
Imports: 
    config (>= 0.3.1),
    golem (>= 0.3.5),
    shiny (>= 1.7.4)
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.1.1
```

**Comment by ColinFay** [comment] 2023-02-08 11:58
Same on linux : 
```
docker run -it rocker/shiny:latest R
> install.packages("remotes")
[...]
> remotes::install_github("thinkr-open/golem")
[...]
> golem::create_golem(package_name = "toto.bidul",path = "hop", open = FALSE)
[...]
> list.files("/hop")
[1] "DESCRIPTION" "dev"         "inst"        "man"         "NAMESPACE"  
[6] "R"          
> readLines("/hop/DESCRIPTION")
 [1] "Package: toto.bidul"                                
 [2] "Title: An Amazing Shiny App"                        
 [3] "Version: 0.0.0.9000"                                
 [4] "Authors@R: "                                        
 [5] "    person(given = \"firstname\","                  
 [6] "           family = \"lastname\","                  
 [7] "           role = c(\"aut\", \"cre\"),"             
 [8] "           email = \"your@email.com\")"             
 [9] "Description: What the package does (one paragraph)."
[10] "License: What license is it under?"                 
[11] "Imports: "                                          
[12] "    config (>= 0.3.1),"                             
[13] "    golem (>= 0.3.5.9001),"                         
[14] "    shiny (>= 1.7.4)"                               
[15] "Encoding: UTF-8"                                    
[16] "LazyData: true"                                     
[17] "RoxygenNote: 7.1.1"

**Comment by Cervangirard** [comment] 2023-02-09 08:30
Hello old friends,

It works for windows if you use package_name for what it is supposed to do :) . package_name is not to be used to make a subfolder. It's only for the package name. in this case you should do : create_golem(path = "hop/toto.bidul") and in this case no problem on windows

I think we can close the issue :)

Sincerely,
big kisses

**Closed** 2023-02-09 12:37 UTC
Labels: bug
